### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by rcurrie**
Merge changes @diekhans has made since we forked into master as the first step in switching back to @maximillianh repo.

### CODE REVIEW

**Comment by diekhans** [comment]
I think this is merge already, lib/pm_pycbio is there in master

**Comment by diekhans** [comment]
oh, doh, you merged it.  I am so pathetic.

**Comment by rcurrie** [comment]
Ahem...I reserve the role of git kook :-) I see you deleted chardot. I deleted bs4 favoring installation from pip. Thoughts?

**Comment by rcurrie** [comment]
Also are you running python2 or python3 for production? I've been using 2 but notice a bunch of future/builtin warnings. If you're on 3 then I may try and move there for this portion as well (the tooling around BRCA is all python3 only)

**Comment by diekhans** [comment]
I did a 2+3 port of only the libraries that need to be included
in other python3 code.  The pubMunch programs ran in python 2,
other programs in py3.

Where things are at in terms of the 2 to 3 switch in the larger
community, I no longer think it is worth trying to make things
both 2+3 compatible.  Anytime I come up against a package that
doesn't support py3, there is usually adware anyway.

That said, porting pubmunch to py3 is going to be a bit of a pain,
because, at least in my experience, the bytes vs str stuff has a lot of
hidden surprises that the tools don't find.

**Pull request merged**
